---
# Copyright (C) 2015 PSP2SDK Project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sudo: false

cache:
  directories:
    - $HOME/devkitPro

before_install:
 - curl -Ls https://download.sourceforge.net/devkitpro/devkitARMupdate.pl | perl; true
 - set -e
 - git clone git://github.com/psp2dev/libs "$PSP2LIBS"

 - git clone -q --single-branch -b all "https://$TOKEN@github.com/psp2sdk/psp2sdk.git" $PREFIX | sed s/$TOKEN/\${TOKEN}/g
 - find $PREFIX/arm-none-eabi/lib -type f ! -name crtend.o -a ! -name libgcc.a -delete

script:
 - aclocal
 - automake --add-missing
 - autoconf

 - mkdir out
 - cd out
 - ../configure $FLAGS || cat config.log
 - make install -j4

 - mkdir fpu
 - cd fpu
 - ../../configure $FLAGS --with-fpu
 - make install -j4
 - cd ..

 - mkdir thumb
 - cd thumb
 - ../../configure $FLAGS --with-thumb
 - make install -j4
 - cd ../..

after_success:
 - cd $PREFIX
 - git add -A arm-none-eabi/lib
 - git config user.name "Travis CI"
 - git config user.email contact@travis-ci.com
 - git commit -qam "multilib dirty-$(git -C .. describe --always)"
 - git push -q origin | sed s/$TOKEN/\${TOKEN}/g

env:
 global:
  - DEVKITPRO="$HOME/devkitPro"
  - DEVKITARM="$DEVKITPRO/devkitARM"
  - PATH="$PATH:$DEVKITARM/bin"
  - PREFIX="$PWD/multilib"
  - PSP2LIBS="$PWD/libs"
  - FLAGS="-q --host=arm-none-eabi --with-headers=$PSP2LIBS/include --prefix=$PREFIX"
  - secure: "Z+7kVFpyzaAqlASVk8J3OGiYAu6aCwLSFJfd+ztzvAIFg2y88lpv0CV1U9E+dwCTfqW8gIeoB100Yl+aCPJQ3EKGbrGHO4J+/vLRBfzLcV5wR4o4mp9ChTRUgBLCoqK67AcB8b6kw3fV3GvefXq0gT/gE52dsD72s/wUcV+8Ozva6SztNhySpBB21F8Fz46yk2idyQX9LtnVyovnS52iucAQCXvd7gaePQ0MtfSkLIMj0Z2Z57Dg7fA2P3mYROo/BBbtCN/9Pw0v8nAZUaKavU9v7VuXywn/pd76/s2vjcumH5REG/1WJ9G5nBE9W63yesKX4HfDI+bdICZAQuRap9/wQ71IZGR7dFI7RsjDryw1lLYVuvJPYPO8TTvdoKUrsXo24r8G5KB6NBXl+9hYMeQkr5Bh1LJSuXbY1xRlMOoh0BP91Y4YBE0BMUWi23XmvZgT7ACumbPMXRYPjpBwEjRBsVafjEh38g96Um011gq0Det9+Jt1rl1G1kLwOmh1GDKp8+mUeILXHarW0X9j7Mqs13ZOw7OYQlP3HE6L13ozYgwJyaeuSyal06UP0p9uxMaXf8qHXI1laRf3k28KJgs3GQA4LMxYqhUwV6UbJTQLYlCO0R+xnGyw6BbLb+bqH/e30ZX+yRL6jxXYIuQDnealqv4AvkbEJWjs2oMTvR0="
